name: Drupal Dev

on:
  pull_request: ~
#  push:
#    branches:
#      - update-drupal-example
#    paths:
#      - 'drupal/**'

env:
  SKPR_USERNAME: ${{ secrets.SKPR_QA_USERNAME }}
  SKPR_PASSWORD: ${{ secrets.SKPR_QA_PASSWORD }}

concurrency:
  group: drupal-dev
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./drupal
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v6

      - name: Setup skpr
        uses: skpr/setup-action@v1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get version
        id: version
        run: |
          version=$(git rev-parse --short HEAD)
          echo "::notice:: Using version $version from git describe"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: ğŸ“¦ Package
        run: skpr package ${{ steps.version.outputs.version }}

      - name: ğŸš€ Deploy
        run: skpr deploy dev ${{ steps.version.outputs.version }}

      - name: ğŸ§¹ Post-deploy
        run: skpr exec dev "drush updb -y"
